version: '3.4'

services:
  web:
    image: abpdockerweb
    ports:
      - 9005:80
    build:
      context: .
      dockerfile: src/AbpDocker.Web/Dockerfile
    depends_on:
      - database

  identityserver:
    image: abpdockeridentityserver
    ports:
      - 9006:80
    build:
      context: .
      dockerfile: src/AbpDocker.IdentityServer/Dockerfile
    depends_on:
      - database

  httpapi:
    image: abpdockerhttpapihost
    ports:
      - 9007:80
    build:
      context: .
      dockerfile: src/AbpDocker.HttpApi.Host/Dockerfile
    depends_on:
      - database

  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes: 
        - database.volume:/var/opt/mssql
    environment:
        SA_PASSWORD: "P@ssw0rd"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "5432:1433"

volumes:
   database.volume:

